routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware(['student.guest','management.guest']);
Route::get('UGAdmission', function() {
	return redirect('/');
});
Route::group(['prefix' => 'student'], function () {
      Route::get('/', function () {
          return redirect('/');
      });
      Route::get('/login', 'StudentAuth\LoginController@showLoginForm')->name('login');
      Route::post('/login', 'StudentAuth\LoginController@login');
      Route::post('/logout', 'StudentAuth\LoginController@logout')->name('logout');

      Route::get('/register', 'StudentAuth\RegisterController@showRegistrationForm')->name('register');
      Route::post('/register', 'StudentAuth\RegisterController@register');

      Route::post('/password/email', 'StudentAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
      Route::post('/password/reset', 'StudentAuth\ResetPasswordController@reset')->name('password.email');
      Route::get('/password/reset', 'StudentAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
      Route::get('/password/reset/{token}', 'StudentAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'management'], function () {
       Route::get('/', function () {
          return redirect('/');
      });
      Route::get('/login', 'ManagementAuth\LoginController@showLoginForm');
      Route::post('/login', 'ManagementAuth\LoginController@login');
      Route::post('/logout', 'ManagementAuth\LoginController@logout')->name('logout');

      Route::get('/register', 'ManagementAuth\RegisterController@showRegistrationForm')->name('register');
      Route::post('/register', 'ManagementAuth\RegisterController@register');

      Route::post('/password/email', 'ManagementAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
      Route::post('/password/reset', 'ManagementAuth\ResetPasswordController@reset')->name('password.email');
      Route::get('/password/reset', 'ManagementAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
      Route::get('/password/reset/{token}', 'ManagementAuth\ResetPasswordController@showResetForm');
});

app/Management.php
<?php

namespace App;

use App\Notifications\ManagementResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Management extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ManagementResetPassword($token));
    }
}

app/transaction_history.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class transaction_history extends Model
{
	protected $table = 'transaction_history';
  protected $fillable = [
      'app_no',
      'invoice_no',
      't_amt',
      't_status',
      't_id',
      'branch_sol_id',
    ];

  /**
     * Get the transaction date in 01/Jan/2017 7:18 am format.
     *
     * @param  date  $value[created_at]
     * @return carbon date
     */
    public function getUpdatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d-M h:i:s a');
    }
}

app/Http/Controllers/Management/CsvuploadController.php
<?php

namespace App\Http\Controllers\Management;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\StudentDetail;
use App\transaction_history;
use App\transaction_tab;

class CsvuploadController extends Controller
{
	/**
     * Create a new controller instance.
     *
     */
    public function __construct()
    {
        $this->middleware('management');
    }

    public function index()
    {
        $error_array = NULL;
        $success_array = NULL;
    	return view('management.csvupload')->with(compact('error_array', 'success_array'));
    }

    public function upload(Request $request)
    {
        $this->validate($request,[

                'csv' => 'required|mimes:csv,txt',
            ]);

    	if($request->file('csv'))
        {
            $file = fopen($request->file('csv'),"r");

            $count = 0;
            $success_array = [];
            $error_array = [];
            while(($line = fgetcsv($file)) !== FALSE)
            {
                    /*$invoice_no = $line[0];
                    $app_no = $line[1];
                    $t_amt = $line[5];
                    $t_id = $line[6];*/
                    $offline_status = StudentDetail::join('transaction_tab','transaction_tab.app_no','student_details.app_no')
                                        ->where('student_details.app_no', '=', $line[1])
                                        ->first();
                    // return $offline_status->status;
                    if($offline_status ){
                        if($offline_status->status == 5 && $offline_status->t_amt == $line[5])
                        {
                            $line[] = $offline_status->status;
                            $line[] = $offline_status->t_amt;
                            $success_array[] = $line;
                        }
                        else
                        {
                            $line[] = $offline_status->status;
                            $line[] = $offline_status->t_amt;
                            $error_array[] = $line;
                        }
                    }else{
                        $line[] = NULL;
                        $line[] = NULL;
                        $error_array[] = $line;/*User not created payment*/
                    }
                }
            /*return $success_array;
            return $error_array;*/
            return view("management/csvupload")->with(compact('error_array', 'success_array'));
        } 
    }

    public function offlinedataupload(Request $request)
    {
        /*return $request->all();*/
        /*return count($request->invoice_no);*/
        try {

            DB::beginTransaction();
            $count = 0;
            for ($i=0; $i < count($request->invoice_no); $i++) {
                transaction_tab::where('app_no', $request->app_no[$i])
                                    ->update([
                                        't_id' => $request->app_no[$i],
                                        't_type' => 'Offline',
                                        'received_amt' => $request->amount[$i],
                                        't_id' => $request->t_id[$i],
                                        't_status' => 'SUCCESS',
                                    ]);

                transaction_history::insert(
                    [

                    'invoice_no'=>  $request->invoice_no[$i],
                    'app_no'=>  $request->app_no[$i],
                    't_amt'=>   $request->amount[$i],
                    't_type'=>'Offline',
                    't_status'=>'SUCCESS',
                    't_id'=> $request->t_id[$i],
                    'bank_ref_no'=> $request->invoice_no[$i],

                    ]);

                StudentDetail::where('app_no', $request->app_no[$i])
                    ->update([

                        'status'=>6

                        ]);
                $count++;
            }
            DB::commit();
            return \Redirect::back()->with('alert', $count.' No of Rows has been Inserted');
        }
        catch(\Exception $e) {

                DB::rollBack();
                /*return $e;*/
                return \Redirect::back()->with('alert', 'CSV file does not matched with required format at row no : '.($count+1) .' FOR : '.substr($e->getMessage(), 0, strpos($e->getMessage(), "for")));
            }


    }
}

        

app/Http/Controllers/Management/DashboardController.php
<?php

namespace App\Http\Controllers\Management;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Student;
use App\StudentDetail;
use App\AcademicDetails;
use DB;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     */
    public function __construct()
    {
        $this->middleware('management');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $register = Student::count();
        $step1 = StudentDetail::where('status', 1)->count();
        $step2 = StudentDetail::where('status', 2)->count();
        $step3 = StudentDetail::where('status', 3)->count();
        $step4 = StudentDetail::where('status', 4)->count();
       // $step5 = StudentDetail::where('status', 5)->count();
        // $ofline = StudentDetail::join('transaction_tab','student_details.app_no','=','transaction_tab.app_no')
        //         ->where('student_details.status',5)
        //         ->where('transaction_tab.t_type','Offline')
        //         ->count();
		$onlinepayment = StudentDetail::join('transaction_tab','student_details.app_no','=','transaction_tab.app_no')
				->where('student_details.status',6)
                ->where('transaction_tab.t_type','online')
                ->sum('transaction_tab.t_amt');
        $step6 = StudentDetail::where('status', 6)->count();
        return view('management.adminboard')->with(compact('register','step1','step2','step3','step4','step6','onlinepayment'));;
    }


    public function counselling_bulk(){



        return view('management.counselling_bulk');
    }

    public function counselling_bulkprint(Request $request){

         // string for the query

        // $user = StudentDetail::join('students','student_details.app_no','=','students.id')
        //         ->join('academic_details','student_details.app_no','=','academic_details.app_no')
        //         ->join('bulk_form','student_details.app_no','=','bulk_form.app_no')
        //         ->select('*','student_details.app_no as application_no')
        //         ->where('bulk_form.board',$request->board_name)
        //         ->where('bulk_form.category',$request->category)
                
        //         ->get();


        $user = DB::table('bulk_form')
                ->join('students','bulk_form.app_no','=','students.id')
                ->join('academic_details','bulk_form.app_no','=','academic_details.app_no')
                ->join('student_details','student_details.app_no','=','bulk_form.app_no')
                ->select('*','student_details.app_no as application_no')
                ->where('bulk_form.board',$request->board_name)
                ->where('bulk_form.category',$request->category)
                ->orderBy('bulk_form.id')
                ->get();

        return view('management.print')->with(compact('user'));
    }


    public function bulksms()
    {

        set_time_limit(0);
        $users = DB::table('sms')->get();



        //return $users;
          //$mobile = $users[0]->ph_no;

        foreach ($users as $user) {
            
            $mobile = $user->ph_no;
            $message = 'Your payment data has been updated from our end. please check your application:BCKV';

            $data = array(
            'authkey' => "113601AINMyMWBSkG857400860",
            'mobiles' =>  $mobile,
            'message' => $message,
            'sender' => "BCKVUG",
            'route' => "4",
            'country' => '91'
        );
        
        $url = "https://control.msg91.com/api/sendhttp.php";

        $ch = curl_init();

        curl_setopt_array($ch, array(
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $data
                //,CURLOPT_FOLLOWLOCATION => true
        ));

        //Ignore SSL certificate verification
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

        //get response
        $output = curl_exec($ch);
        curl_close($ch);
        }

        return redirect()->back() ->with('alert', 'Done!');

     }



      public function calculationcorrection()

    {

        set_time_limit(0);
        $users = AcademicDetails::get();

        $count = 0;

        foreach ($users as $key => $user) {

            $app_no = $user->app_no;
            $board_name = $user->board_name;
            $total_mark = $user->total_mark;
            $total_fullmarks = $user->total_fullmarks;

            $class10mrk = $user->class10mrk;
            $class10fm = $user->class10fm;

            $classten_percentage = (($class10mrk * 100)/$class10fm);
            $classten_percentage = number_format($classten_percentage,3);


            $arr1=explode('.', $classten_percentage);
            //print_r($arr);
            /*$firsr=$arr[0];
            echo $firsr;
            $sec=$arr[1];*/
            list($a, $b) = $arr1;
            //echo $a;
            $fir1=$a;
            $sec1 = substr($b,0,2);

            $classten_percentage_final=$fir1.'.'.$sec1;  //value




            $classten_weightage = (($classten_percentage_final * 20)/100);
            $classten_weightage = number_format($classten_weightage,3); 

            $arr1=explode('.', $classten_weightage);
            //print_r($arr);
            /*$firsr=$arr[0];
            echo $firsr;
            $sec=$arr[1];*/
            list($a, $b) = $arr1;
            //echo $a;
            $fir1=$a;
            $sec1 = substr($b,0,2);

            $classten_weightage_final=$fir1.'.'.$sec1;   //value



            







            // if ( $board_name == "WBCHSE" || $board_name == "Other Board") {


            //     $classtwelve_percentage = (($total_mark * 100)/$total_fullmarks);

            //     } 

            // else {

                $classtwelve_percentage = (($total_mark * 100)/$total_fullmarks);
                
            // }
                $classtwelve_percentage = number_format($classtwelve_percentage,3);

                $arr1=explode('.', $classtwelve_percentage);
                //print_r($arr);
                /*$firsr=$arr[0];
                echo $firsr;
                $sec=$arr[1];*/
                list($a, $b) = $arr1;
                //echo $a;
                $fir1=$a;
                $sec1 = substr($b,0,2);

                $classtwelve_percentage_final=$fir1.'.'.$sec1;  //value

            


                $classtwelve_weightage = (($classtwelve_percentage_final * 80)/100);

                $classtwelve_weightage = number_format($classtwelve_weightage,3);


                $arr2=explode('.', $classtwelve_weightage);
                //print_r($arr);
                /*$firsr=$arr[0];
                echo $firsr;
                $sec=$arr[1];*/
                list($a, $b) = $arr2;
                //echo $a;
                $fir2=$a;
                $sec2 = substr($b,0,2);
                $classtwelve_weightage_final=$fir2.'.'.$sec2;



                $mark_index = ($classten_weightage_final + $classtwelve_weightage_final);




                AcademicDetails::updateOrCreate(['app_no' => $app_no], 
                [
                    
                    
                    'percentage'    => $classtwelve_percentage_final,
                    'classten_percentage'    => $classten_percentage_final,
                    'classten_weightage_final'    => $classten_weightage_final,
                    'classtwelve_weightage_final'    => $classtwelve_weightage_final,
                    'mark_index'    => $mark_index,
                ]
             );

                $student_array[] = $app_no;


            # code...
        }

         return view('management.calculationdone')->with(compact('student_array'));

    }
}

app/Http/Controllers/Management/ImageController.php
<?php

namespace App\Http\Controllers\Management;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ImageController extends Controller
{
    /**
     * Create a new controller instance.
     *
     */
    public function __construct()
    {
        $this->middleware('management');
    }

    /**
     * Show Images.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($app_no, $name)
    {
    	$path = $app_no.'/'.$name;
    	$content = \Storage::exists($path);

    	if($content){
            return \Response::make(\Storage::disk('local')->get($path), 200,[
                'Content-Type' => 'image/jpg'
            ]);
    		// $url = \Storage::url($path);
    		// return response()->file($url);
    	}
    	return response()->file('images/bckv-logo.png');
    }
}

resources/views/management/adminboard.blade.php
@extends('management.layout.auth')

@section('content')
<div class="container">
    <div class="row text-center">
        <div class="col-sm-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title pull-left">Total Registration<h4>
                </div>
                <div class="panel-body">
                    <b>{{ $register }}</b>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h6 class="panel-title pull-left">Personal   |  10th & 10+2<h5>
                </div>
                <div class="panel-body">
                    <b class="pull-left">{{ $step1 }}</b> 
                    <b class="pull-right"> {{ $step2 }}</b>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title pull-left">Image Uploaded<h4>
                </div>
                <div class="panel-body">
                    <b>{{ $step3 }}</b>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title pull-left">Form Submited<h4>
                </div>
                <div class="panel-body">
                    <b>{{ $step4 }}</b>
                </div>
            </div>
        </div>
        {{-- <div class="col-sm-2">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h4 class="panel-title pull-left">Offline Due<h4>
                </div>
                <div class="panel-body">
                    <b>{{ $ofline }}</b>
                </div>
            </div>
        </div> --}}
        <div class="col-sm-3">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title pull-left">Successfull<h4>
                </div>
                <div class="panel-body">
                    <b>{{ $step6 }}</b>
                </div>
            </div>
        </div>
		<div class="col-sm-4">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title pull-left">SUCCESSFUL ONLINE PAYMENT<h4>
                </div>
                <div class="panel-body">
                    <b>₹ {{ $onlinepayment }}</b>
                </div>
            </div>
        </div>
    </div>
</div>
<hr/>
<div style="min-height: 400px;" align="center" class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-6">
        <div class="list-group">
            <a href="{{ url('/management/meritlist') }}" class="list-group-item">
            <h4>Check Merit-List</h4></a>
        </div>
       {{--  <div class="list-group">
            <a href="{{ url('/management/csvupload') }}" class="list-group-item">
            <h4>Challan Upload</h4></a>
        </div> --}}
        


        {{-- <div class="list-group">
            <a href="{{ url('/management/meritlistWBCHSEOTHERS') }}" class="list-group-item">
            <h4>Combined Merit List for WBCHSE / OTHERS Board</h4></a>
        </div> --}}
        <div class="list-group">
            <a href="{{ url('/management/printmeritlist') }}" class="list-group-item">
            <h4>Print Merit List (for Publication)</h4></a>
        </div>


        

        <div class="list-group">
            <a href="{{ url('/management/checkstatus') }}" class="list-group-item">
            <h4>Check Application Status</h4></a>
        </div>



    </div>
    <div class="col-md-4">

        <div class="list-group">
            <a href="{{ url('/management/counselling_bulk') }}" class="list-group-item">
            <h4>Counselling Bulk</h4></a>
        </div>

        {{-- <div class="list-group">
            <a href="{{ url('/management/bulksms') }}" class="list-group-item">
            <h4>Bulk SMS Send</h4></a>
        </div> --}}

    </div>
    
</div>



<script type="text/javascript">
    var msg = '{{Session::get('alert')}}';
    var exist = '{{Session::has('alert')}}';
    if(exist){
      alert(msg);
    }
  </script>
@endsection

resources/views/management/bulkprint.blade.php
<html>
    <title>{{ config('app.name', 'BCKV') }}</title>
    <body onload="document.frm1.submit()">
        <form action="{{ url('management/bulkprint') }}" name="frm1" method="POST">
            {{ csrf_field() }}
            <input id="students_id" type="hidden" name="students_id" value="{{ app('request')->input('a') }}">
        </form>
    </body>
</html>

resources/views/management/calculationdone.blade.php
@extends('management.layout.auth')

@section('content')
<div class="hidden-print" style="text-align: center; margin-bottom: 30px;">
    <p style="color: red;">Kindly Choose Scale as 98</p>
    <button class="btn btn-primary" onclick="myPrint()">Print this page</button>
</div>

@if(count($student_array) != 0)


	
		@foreach ($student_array as $students_id)
		
			<h1>Application ID - {{ $students_id }}</h1>
			
		
		@endforeach
	



	@else
<h1 style="text-align: center;">NO RECORD FOUND! </h1>
@endif

<script>
    function myPrint() {
        window.print();
    }
</script>
<style>
@media print {
	.page-break { display: block; page-break-before: always; }
	img {
	    max-width:100%;
	    max-height:900px;
	}
	h1{
		text-align:center;
	}
}
</style>
@endsection

resources/views/management/management.blade.php
@extends('management.layout.auth')
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left">Get Student Information<h4>
                    {{-- <div class="btn-group pull-right">
                        <a type="button" class="btn btn-success float-right" href="{{ url('management/home') }}">Back to Dashboard</a>
                    </div> --}}
                </div>
                <div class="panel-body">
                    <form>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" name="app_no" id="app_no" value="@if(!empty($student)){{$student->id}}@endif" placeholder="Application No. i.e. 12345" />
                        </div>
                        <div class="col-sm-7">
                            <input id="submit" type="submit" class="btn btn-primary" value="Get Information">
                            @if(!empty ( $student ) && $student->status>3)
                            <input type="button" id="print" class="btn btn-success" onclick="printed()" value="View Application">
                            <script>
                                function printed(){
                                    window.open("{{ url('management/singleprint') }}?a={{$student->id}}", "Application Preview", "toolbar=no,scrollbars=yes,resizable=yes,top=10,left=10,width=1300,height=600");
                                }  
                            </script>
                            @endif
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-12" style="min-height: 300px">
            @if(!empty ( $student ))
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left">Student Personal Details [ U{{ $student->id }} ] <h4>
                </div>
                <div class="panel-body">
                    <div class="tabtable-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Father Name</th>
                                <th>Mother Name</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Category</th>
                                <th>DOB</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ $student->name}}</td>
                                <td>{{ $student->father_name}}</td>
                                <td>{{ $student->mother_name}}</td>
                                <td>{{ $student->email}}</td>
                                <td>{{ $student->mobile_number}}</td>
                                <td>{{ $student->category}}</td>
                                <td>{{ $student->date_of_birth}}</td>
                                @if(empty($student->status))
                                    <td> Only Registered, {{ $student->created_at }}</td> 
                                @elseif($student->status==1)
                                    <td class="warning">Personal Info</td>
                                @elseif($student->status==2)
                                    <td class="warning">Personal, Academic</td>
                                @elseif($student->status==3)
                                    <td class="danger">Waiting for Final submit</td>
                                @elseif($student->status==4)
                                    <td class="danger">Payment Due</td>
                                @elseif($student->status==5)
                                    <td class="warning">Payment Due [ {{$payment->t_type}} ] </td>
                                @elseif($student->status==6)
                                    <td class="success"> Successfully Submitted</td>
                                @endif
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @endif

            @if(!empty ( $payment ))
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left">Student Payment Details<h4>
                </div>
                <div class="panel-body">
                    <div class="tabtable-responsive">
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <th>Transaction Type</th>
                                <th>Ammount</th>
                                <th>Transaction Status</th>
                                <th>Invoice ID</th>
                                <th>Transaction ID</th>
                                <th>Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ strtoupper($payment->t_type) }}</td>
                                <td>{{ $payment->t_amt}}</td>
                                <td><b>{{ $payment->t_status}}</b></td>
                                <td>{{ $payment->id}}</td>
                                <td>{{ $payment->t_id}}</td>
                                <td>{{ $payment->updated_at}}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @endif

            @if(!$history->isEmpty())
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left">Transcation History<h4>
                </div>
                <div class="panel-body">
                    <div class="tabtable-responsive">
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <th>Transaction Type</th>
                                <th>Invoice ID</th>
                                <th>Transaction ID</th>
                                <th>Ammount</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th>Auth Status</th>
                                <th>Auth ERROR</th>
                                <th>Bank ID</th>
                                <th>Bank Ref. No.</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($history as $h)
                            <tr>
                                <td>{{ $h['t_type']}}</td>
                                <td>{{ $h->invoice_no}}</td>
                                <td>{{ $h->t_id}}</td>
                                <td>{{ $h->t_amt}}</td>
                                <td><b>{{ $h->t_status}}</b></td>
                                <td>{{ $h->updated_at}}</td>
                                <td>{{ $h->auth_status}}</td>
                                <td>{{ $h->error_descrip}}</td>
                                <td>{{ $h->bank_id}}</td>
                                <td>{{ $h->bank_ref_no}}</td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>

    <div class="row" style="margin-bottom: 20px">
        <div class="col-sm-11">
            <div class="btn-group pull-right">
                <a type="button" class="btn btn-success float-right" href="{{ url('management/home') }}">Back to Dashboard</a>
            </div>
        </div>
    </div>
</div>

@endsection